name: make test

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  make_test:
    name: make test ${{ matrix.os }} (python ${{ matrix.python }}) (perl ${{ matrix.perl }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-latest, ubuntu-18.04, ubuntu-latest]
        python: [2.7, 3]
        perl: [5.12, latest]
        exclude:
        - python: 2.7
          perl: latest
        - python: 3
          perl: 5.12

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'
    - name: setup-perl Windows ${{ matrix.perl }}
      if: runner.os == 'Windows'
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}       
        distribution: strawberry

    - name: setup-perl Linux ${{ matrix.perl }}
      if: runner.os == 'Linux'
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}       

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y libreadline6-dev libcurl4-openssl-dev

    - name: Environment check
      run: |
        echo "------------- check g++ version -------------"
        g++ --version
        echo "------------- perl version -------------"
        perl --version
        echo "------------- Time::HiRes module -------------"
        perl -e "use Time::HiRes;"
        echo "------------- Compress::Zlib module -------------"
        perl -e "use Compress::Zlib;"
        echo "------------- python version -------------"
        python -V

    - name: Run Tests
      run: make test
